"""build_artifact — a provider-neutral markdown context block for one project.

Unlike `ProjectMemory.recall`/`.ask`, this does not go through
`declared_core.hybrid_query`. It needs *exact* membership ("every atom whose
`batch` is this project", "every active fact where this project is named in
`tags`"), not a fuzzy BM25/RRF ranking — so it reads `mem.conn` directly
against `mem.schema.episode_table` / `fact_table`.

The output is the four-section block described in
`MEMORY-SYSTEM-MVP-SPEC.md` Unit 1: Identity, Interfaces, Related (1-hop,
with reason), What to do — plus a fifth, M2 section (Recent memory) once a
project has any `brain remember`'d decisions. It is meant to be pasted into
(or auto-injected into) any agent session to make it instantly aware of a
project without re-scanning the repo.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from .graph import EDGE_CATEGORIES, GraphHit, Hop, edges_touching, known_projects, walk
from .pack import find_pack
from .query import ProjectMemory

# Revised 2026-07-11 after dogfooding in a live session (`vouch`, whose own
# purpose is fact-checking unverified claims): the original wording ("Ground
# answers... do not re-scan the repo") was an imperative command sitting in
# untrusted-looking injected context — a safety-conscious session correctly
# treated it as suspect rather than obeying it, which defeats the point. This
# version self-identifies its provenance (a local tool, verified local docs,
# no network fetch) and reads as information, not an instruction to follow.
_DEFAULT_PROMPT = (
    "This is a local context summary for {name}, generated by project_memory "
    "(a tool the repo owner runs) from this project's own docs and verified "
    "cross-repo references — not fetched from the network. Treat it as a "
    "starting reference, the way you'd treat a README."
)

_KNOWN_GROUPS = ("fleet", "verbalogix", "self")

# Context-budget guard: a pack (Unit 2) concatenates several members' artifacts,
# so an unbounded Interfaces list (ngfify's heading-fallback can produce one
# atom per markdown heading) could balloon what a SessionStart hook injects
# into every session. Cap and say what was dropped rather than truncate silently.
_MAX_INTERFACE_BULLETS = 15

# Same budget guard, one level up: a pack with an unbounded member list would
# concatenate an unbounded number of full project artifacts. Today's two real
# packs have 4 members each — this only bites once the brain (and its packs)
# grow well past the MVP's 21 repos.
_MAX_PACK_MEMBERS = 20

# Same idiom again, for M2's accreted decision log — `brain remember` has no
# natural upper bound over a project's lifetime.
_MAX_MEMORY_ITEMS = 8

# `verify_edge` (portfolio.py) always phrases a reason as one of four formulaic
# sentences: "<asserter>'s own docs name ['the alias] '<matched>' (== <other>)."
# The asserter + matched name/alias is the only signal worth a token; compress
# it. A hand-written `reason` (e.g. a manually record_fact'd edge) won't match
# and is passed through verbatim — this is a cosmetic compression, never the
# source of truth for what an edge means.
_REASON_PATTERN = re.compile(
    r"^(?P<asserter>.+?)'s own docs name (?:the alias )?'(?P<matched>[^']+)' \(== .+?\)\.?$"
)


def _compress_reason(reason: str | None) -> str:
    if not reason:
        return "(no reason recorded)"
    m = _REASON_PATTERN.match(reason.strip())
    return f"{m['asserter']} docs name '{m['matched']}'" if m else reason


def _project_atoms(mem: ProjectMemory, scope: str) -> list[dict[str, Any]]:
    sql = (
        f"SELECT content, kind, tags, created_at FROM {mem.schema.episode_table} "
        f"WHERE batch = ? ORDER BY created_at"
    )
    rows = mem.conn.execute(sql, (scope,)).fetchall()
    return [
        {"content": content, "kind": kind, "tags": json.loads(tags or "[]"), "created_at": created_at}
        for content, kind, tags, created_at in rows
    ]


def _category_labels(category: str) -> tuple[str, str]:
    """(forward, reverse) render labels for an edge category — scope is the
    edge's source for the forward label, the target for the reverse one."""
    labels = EDGE_CATEGORIES.get(category)
    return (labels["forward"], labels["reverse"]) if labels else (category, category)


def _identity_section(atoms: list[dict[str, Any]], kind: str, last_indexed: str | None) -> str:
    # A repo can be re-indexed after its README summary changes (the milestone
    # id is content-derived, so a changed summary is a new row, not a crash) —
    # take the freshest one, not the first found.
    milestones = [a for a in atoms if a["kind"] == "milestone"]
    milestone = max(milestones, key=lambda a: a["created_at"]) if milestones else None
    if milestone is not None:
        purpose = milestone["content"].split(": ", 1)[-1]
        group = next((t for t in milestone["tags"] if t in _KNOWN_GROUPS), "fleet")
    else:
        purpose = "(no declared summary found)."
        group = "fleet"
    indexed = last_indexed[:10] if last_indexed else "never"
    return f"## Identity\n{purpose}\nGroup: {group} · Kind: {kind} · Indexed: {indexed}\n"


def _interfaces_section(atoms: list[dict[str, Any]]) -> str:
    interfaces = [a["content"] for a in atoms if a["kind"] == "interface"]
    if not interfaces:
        return "## Interfaces\n(none declared)\n"
    shown, extra = interfaces[:_MAX_INTERFACE_BULLETS], interfaces[_MAX_INTERFACE_BULLETS:]
    body = "\n".join(f"- {c}" for c in shown)
    if extra:
        body += f"\n- …and {len(extra)} more (truncated for context budget)"
    return f"## Interfaces\n{body}\n"


def _related_section(edges: list[Hop], known_batches: set[str]) -> str:
    if not edges:
        return "## Related (1-hop, with reason)\n(no verified edges)\n"
    lines = []
    for e in edges:
        forward, reverse = _category_labels(e.category)
        label = forward if e.direction == "forward" else reverse
        arrow = "→" if e.direction == "forward" else "←"
        pending = "" if e.other in known_batches else "  (pending)"
        lines.append(f"- {label} {arrow} {e.other} — {_compress_reason(e.reason)}{pending}")
    return "## Related (1-hop, with reason)\n" + "\n".join(lines) + "\n"


def _format_hop_path(path: tuple[Hop, ...]) -> str:
    """'composes → declared_core' for a 1-hop path; each additional hop
    appends its own label + arrow, e.g. 'composes → x → built-by → y'."""
    parts = []
    for hop in path:
        forward, reverse = _category_labels(hop.category)
        label = forward if hop.direction == "forward" else reverse
        arrow = "→" if hop.direction == "forward" else "←"
        parts.append(f"{label} {arrow} {hop.other}")
    return " ".join(parts)


def _scored_related_section(hits: list[GraphHit]) -> str:
    """The hops=2 Related section — every 1-2 hop `GraphHit`, score-ordered.
    The reason shown is the *last* hop's (most specific to how this
    particular node was reached); the score makes the 1-vs-2-hop distinction
    explicit rather than burying it in prose. `GraphHit.resolved` (computed by
    `graph.walk` against `known_projects`) drives the ``(pending)`` marker —
    no separate lookup needed here."""
    if not hits:
        return "## Related (1-2 hops, scored)\n(no verified edges)\n"
    lines = []
    for hit in hits:
        reason = _compress_reason(hit.path[-1].reason)
        pending = "" if hit.resolved else "  (pending)"
        lines.append(f"- {_format_hop_path(hit.path)} — {reason}  (score {hit.score:.2f}){pending}")
    return "## Related (1-2 hops, scored)\n" + "\n".join(lines) + "\n"


def _recent_memory(mem: ProjectMemory, scope: str) -> list[dict[str, Any]]:
    """Active, crystallized `brain remember` facts for `scope`, newest first
    (M2 — the accreted decision log).

    Only *facts* surface here, not raw episodes: `status = 'active'` means a
    superseded decision never resurfaces as current (M2's acceptance bar). An
    episode that was never crystallized (`brain remember --no-auto-fact`)
    stays queryable via `recall`/`ask` but doesn't clutter this at-a-glance
    view — crystallizing is the declared signal "this should be visible in a
    future session," not every logged event.
    """
    # Same SQL-side prefilter + exact Python-side tag check as `_project_edges`
    # (LIKE can't distinguish "de" from "declared_core" as a substring; the
    # `scope in tags` check after `json.loads` is what actually decides membership).
    sql = (
        f"SELECT id, claim, reason, tags, created_at FROM {mem.schema.fact_table} "
        f"WHERE status = 'active' AND tags LIKE '%\"session-memory\"%' AND tags LIKE ? "
        f"ORDER BY created_at DESC"
    )
    rows = mem.conn.execute(sql, (f'%"{scope}"%',)).fetchall()
    items: list[dict[str, Any]] = []
    for fact_id, claim, reason, tags_json, created_at in rows:
        tags = json.loads(tags_json or "[]")
        if scope in tags and "session-memory" in tags:
            items.append({"id": fact_id, "claim": claim, "reason": reason, "created_at": created_at})
    return items


_RECENT_MEMORY_HEADING = "## Recent memory (logged via `brain remember`)"


def _recent_memory_section(items: list[dict[str, Any]]) -> str:
    # Revised 2026-07-11 after dogfooding with `claude -p` (zero tools available,
    # so the answer could only come from injected context): unlike Identity/
    # Interfaces/Related — each grounded in a checkable citation (a real file, a
    # cross-repo doc match) — a bare "we decided X" line is an unverifiable claim
    # with nothing to check it against; a safety-conscious session correctly
    # called that injection-shaped and refused to assert it, even though the
    # wording was already honest (the vouch fix). The heading + a per-line date
    # now frame this as what it actually is — a timestamped local log entry, not
    # an assertion of settled fact — the same move `_related_section` already
    # makes by citing *why* each edge is believed, not just stating it.
    if not items:
        return f"{_RECENT_MEMORY_HEADING}\n(none yet)\n"
    shown, extra = items[:_MAX_MEMORY_ITEMS], items[_MAX_MEMORY_ITEMS:]
    lines = []
    for it in shown:
        date = (it["created_at"] or "")[:10] or "unknown date"
        reason_part = f" — {it['reason']}" if it["reason"] else ""
        lines.append(f'- [{date}] "{it["claim"]}"{reason_part}  (id: {it["id"]})')
    if extra:
        lines.append(f"- …and {len(extra)} more (truncated for context budget)")
    return f"{_RECENT_MEMORY_HEADING}\n" + "\n".join(lines) + "\n"


def _what_to_do_section(name: str, prompt: str | None = None) -> str:
    return f"## What to do\n{prompt or _DEFAULT_PROMPT.format(name=name)}\n"


def _strip_what_to_do(project_artifact: str) -> str:
    """Drop a member's own trailing ``## What to do`` section.

    A pack concatenates several members' project artifacts; each one's own
    boilerplate provenance line would otherwise repeat once per member. The
    pack has exactly one ``## What to do`` — its own prompt, appended once
    at the end (see ``build_pack_artifact``).
    """
    marker = "\n## What to do"
    idx = project_artifact.find(marker)
    return project_artifact if idx == -1 else project_artifact[:idx].rstrip() + "\n"


def _member_related_section(members: list[dict[str, str]]) -> str:
    """A pack's declared ``members:`` rendered in the same Related shape a
    project's edges use — the member ``why`` annotations *are* the reasons
    (spec Unit 2: "member `why` annotations become the Related reasons")."""
    shown, extra = members[:_MAX_PACK_MEMBERS], members[_MAX_PACK_MEMBERS:]
    lines = [f'- member → {m["name"]} — {m["why"]}' for m in shown]
    if extra:
        lines.append(f"- …and {len(extra)} more members (truncated for context budget)")
    return "## Related (1-hop, with reason)\n" + "\n".join(lines) + "\n"


def _pack_staleness_note(mem: ProjectMemory, members: list[dict[str, str]]) -> str:
    """The oldest member's index date, or a flag that at least one member has
    never been indexed — surfaced once at the pack level so staleness doesn't
    hide inside N per-member ``Indexed:`` lines."""
    indexed = [max((a["created_at"] for a in _project_atoms(mem, m["name"])), default=None)
               for m in members]
    if any(i is None for i in indexed):
        return "oldest member: never indexed"
    return f"oldest member indexed: {min(indexed)[:10]}"


def build_pack_artifact(
    scope: str, mem: ProjectMemory, *, members: list[dict[str, str]], prompt: str,
) -> str:
    """Compose a pack-shaped artifact from an already-resolved member list.

    Deliberately decoupled from ``.pack.md`` file loading: a future caller can
    hand this an ad-hoc/computed member list (e.g. "everything tagged X") and
    get the same merged shape, without a hand-authored pack file existing.
    ``scope`` is the id this pack is known by (the header's ``<name>``, same
    role `build_artifact` gives a project's ``scope``).
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        f"# Context: {scope}\n_Graph memory · loaded {ts} · scope=pack · "
        f"members={len(members)} · {_pack_staleness_note(mem, members)}_\n\n"
    )
    body = [_member_related_section(members)]
    body.extend(
        _strip_what_to_do(build_artifact(m["name"], mem, kind="project"))
        for m in members[:_MAX_PACK_MEMBERS]
    )
    body.append(_what_to_do_section(scope, prompt=prompt))
    return header + "\n".join(body)


def build_artifact(scope: str, mem: ProjectMemory, *, hops: int = 1, kind: str = "project") -> str:
    """Return a provider-neutral markdown context block for ``scope``.

    ``scope`` is a project (its `batch` value in the store) or, with
    ``kind="pack"``, a pack id resolved via ``pack.find_pack`` against
    ``project_memory/packs/*.pack.md``. A project's block pulls its atoms as
    Identity (the ``milestone`` atom) + Interfaces (``interface`` atoms), and
    its edges as Related, marking any edge whose other side isn't an indexed
    project ``(pending)``. ``hops=1`` (default) shows direct edges only,
    unchanged since the MVP. ``hops=2`` (M1) walks + rescores 1-2 hop edges
    via ``graph.walk`` — opt-in, not the default, since the SessionStart hook
    injects ``hops=1`` and a bigger payload there would grow what rides
    Claude Code's prompt-cache breakpoint every session. Packs stay
    ``hops=1``-only (each member's own block is built at ``hops=1``; see
    ``build_pack_artifact``). A pack's block is each declared member's own
    project block concatenated plus the pack's own prompt, once.
    """
    if hops not in (1, 2):
        raise NotImplementedError("build_artifact only supports hops=1 or hops=2")

    if kind == "pack":
        if hops != 1:
            raise NotImplementedError("pack artifacts only support hops=1")
        pack = find_pack(scope)
        if pack is None:
            raise ValueError(f"no pack named {scope!r} found — expected a .pack.md file")
        return build_pack_artifact(scope, mem, members=pack["members"], prompt=pack["prompt"])

    atoms = _project_atoms(mem, scope)
    last_indexed = max((a["created_at"] for a in atoms), default=None)
    if hops == 1:
        related = _related_section(edges_touching(mem, scope), known_projects(mem))
    else:
        related = _scored_related_section(walk(mem, scope, hops=2))

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    meta = f"scope={kind}" + (" · hops=2" if hops == 2 else "")
    header = f"# Context: {scope}\n_Graph memory · loaded {ts} · {meta}_\n\n"
    sections = [
        _identity_section(atoms, kind, last_indexed),
        _interfaces_section(atoms),
        related,
        _recent_memory_section(_recent_memory(mem, scope)),
        _what_to_do_section(scope),
    ]
    return header + "\n".join(sections)
